### ISSUE TITLE
something not found :(

### ISSUE THREAD

**Issue by jamie-smith8** [jamie-smith8/jamiesmithdesign#14]
@thomasjbradley 

everything has been committed. 
I tried it on p-eco to see and it broke. 

help :(

**Comment by thomasjbradley** [comment]
There's a couple things going on:

1—The HREF isn't correct inside the link, here on this line:
https://github.com/jamie-smith8/jamiesmithdesign/blob/gh-pages/index.html#L139

It should be:

``` html
 <a href="{{site.baseurl}}/p-eco/">
```

_Notice how I removed `.html` and added `{{site.baseurl}}/`._

---

 2—The URLs for all the CSS files should also have `site.baseurl` in front of them, here in the `default.html`:
https://github.com/jamie-smith8/jamiesmithdesign/blob/gh-pages/_layouts/default.html#L7-L9
