### ISSUE TITLE
image 404 not found

### ISSUE THREAD

**Issue by jamie-smith8** [jamie-smith8/jamiesmithdesign#15]
@thomasjbradley 

my image is in the correct folder, named appropriately and {{site.baseurl}} 

for the life of me I cannot figure out why it is broken. 

![screenshot 2015-12-11 08 08 29](https://cloud.githubusercontent.com/assets/6372772/11744474/ad39d740-9fde-11e5-9d2b-cb8a0a84967f.png)

**Comment by thomasjbradley** [comment]
There's a slash (`/`) missing between `{{site.baseurl}}` and `images`.

**Comment by jamie-smith8** [comment]
of course it's that easy. thank you!
